package com.pantalasa.sdhybc.bd.tablas

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "cedulas")
data class Cedula(
    @PrimaryKey(autoGenerate = true) val id: Long = 0, // Autoincremental
    val ambito: Int,
    val idWeb: Int,
    val usuarioId: Int,
    val municipioNum: String,
    val municipioNom: String,
    val localidadNum: String,
    val localidadNom: String,
    val unidad: String,
    val asistSoc: String,
    val tipoLoc: String,
    val sedeVm: Int,
    val sedeVk: Int,
    val sedePm: Int,
    val sedePk: Int,
    val subsVm: Int,
    val subsVk: Int,
    val subsPm: Int,
    val subsPk: Int,
    val fecRegCed: Long, // Fecha como timestamp (Long)
    val techoConc: Int,
    val techoGalv: Int,
    val techoMade: Int,
    val techoCart: Int,
    val techoOtro: Int,
    val pareTabiq: Int,
    val pareAdobe: Int,
    val pareBlock: Int,
    val pareMader: Int,
    val parePiedr: Int,
    val pareCarto: Int,
    val pisoCemen: Int,
    val pisoMader: Int,
    val pisoTierr: Int,
    val pisoPiedr: Int,
    val agUsoPota: Int,
    val agUsoNori: Int,
    val agUsoRio: Int,
    val agUsoLluv: Int,
    val agConPota: Int,
    val agConPuri: Int,
    val agConHerv: Int,
    val agConClor: Int,
    val agConFilt: Int,
    val excFoSep: Int,
    val excLetri: Int,
    val excRasSu: Int,
    val combGas: Int,
    val combCar: Int,
    val combLen: Int,
    val combOtr: Int,
    val basRedM: Int,
    val basEnte: Int,
    val basCieAb: Int,
    val basInci: Int,
    val alumRedE: Int,
    val alumVela: Int,
    val alumQuin: Int,
    val alumPlaS: Int,
    val numHab: Int,
    val recam: Int,
    val estan: Int,
    val comed: Int,
    val multi: Int,
    val cocin: Int,
    val fecRegViv: Long, // Fecha como timestamp (Long)
    val pueIndTara: Int,
    val pueIndTepe: Int,
    val pueIndWuar: Int,
    val pueIndPima: Int,
    val pueIndMeno: Int,
    val pueIndOtro: Int,
    val derechINSABI: Int,
    val derechIMSS: Int,
    val derechISSSTE: Int,
    val derechPEMEX: Int,
    val derechSEDENA: Int,
    val derechOtro: Int,
    val numPerros: Int,
    val numGatos: Int,
    val numOtros: Int,
    val sisSalINSABI: Int,
    val sisSalIMSS: Int,
    val sisSalISSSTE: Int,
    val sisSalPEMEX: Int,
    val sisSalSEDENA: Int,
    val sisSalOtro: Int,
    val sisSalMedPar: Int,
    val sisSalCliPar: Int,
    val sisSalParter: Int,
    val sisSalCurand: Int,
    val sisSalYerber: Int,
    val sisSalHueser: Int,
    val sisSalBotica: Int,
    val comentario: String,
    val fecRegGen: Long, // Fecha como timestamp (Long)
    val numInteg: Int,
    val origCapt: String
)